# This is a basic workflow to help you get started with Actions

name: testing

# Controls when the workflow will run
on: workflow_dispatch

jobs: 
  first-job:
    runs-on: ubunru-latest
    steps:
      - name: Print greeting
        run: echo "hello here"
      - name: Print goodbye
        run: echo "byeee"
      
  
